-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.avaliacoes
(
    id serial NOT NULL,
    venda_id integer,
    produto_id integer,
    avaliador_id integer NOT NULL,
    avaliado_id integer NOT NULL,
    tipo_avaliado character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nota integer NOT NULL,
    comentario text COLLATE pg_catalog."default",
    data_avaliacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    data_resposta timestamp with time zone,
    resposta_avaliado text COLLATE pg_catalog."default",
    util_count integer DEFAULT 0,
    denunciada boolean DEFAULT false,
    CONSTRAINT avaliacoes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.carrinho_compras
(
    id serial NOT NULL,
    usuario_id integer NOT NULL,
    produto_id integer NOT NULL,
    quantidade integer NOT NULL,
    data_adicionado timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT carrinho_compras_pkey PRIMARY KEY (id),
    CONSTRAINT carrinho_compras_usuario_id_produto_id_key UNIQUE (usuario_id, produto_id)
);

CREATE TABLE IF NOT EXISTS public.categorias_produtos
(
    id serial NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    icone character varying(255) COLLATE pg_catalog."default",
    ativo boolean DEFAULT true,
    ordem_exibicao integer DEFAULT 0,
    CONSTRAINT categorias_produtos_pkey PRIMARY KEY (id),
    CONSTRAINT categorias_produtos_nome_key UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS public.comissoes_config
(
    id serial NOT NULL,
    vendedor_id integer,
    percentual_plataforma numeric(5, 2) NOT NULL DEFAULT 40.00,
    percentual_vendedor numeric(5, 2) NOT NULL DEFAULT 30.00,
    percentual_funcionario numeric(5, 2) NOT NULL DEFAULT 30.00,
    data_configuracao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ativo boolean DEFAULT true,
    CONSTRAINT comissoes_config_pkey PRIMARY KEY (id),
    CONSTRAINT comissoes_config_vendedor_id_key UNIQUE (vendedor_id)
);

CREATE TABLE IF NOT EXISTS public.funcionarios_vinculos
(
    id serial NOT NULL,
    vendedor_id integer NOT NULL,
    funcionario_id integer NOT NULL,
    comissao_funcionario numeric(5, 2) DEFAULT 50.00,
    ativo boolean DEFAULT true,
    data_inicio date DEFAULT CURRENT_DATE,
    data_fim date,
    CONSTRAINT funcionarios_vinculos_pkey PRIMARY KEY (id),
    CONSTRAINT funcionarios_vinculos_vendedor_id_funcionario_id_key UNIQUE (vendedor_id, funcionario_id)
);

CREATE TABLE IF NOT EXISTS public.itens_venda
(
    id serial NOT NULL,
    venda_id integer NOT NULL,
    produto_id integer NOT NULL,
    quantidade integer NOT NULL,
    preco_unitario numeric(10, 2) NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    CONSTRAINT itens_venda_pkey PRIMARY KEY (id),
    CONSTRAINT itens_venda_venda_id_produto_id_key UNIQUE (venda_id, produto_id)
);

CREATE TABLE IF NOT EXISTS public.jogos_plataformas
(
    id serial NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    icone_url character varying(255) COLLATE pg_catalog."default",
    ativo boolean DEFAULT true,
    CONSTRAINT jogos_plataformas_pkey PRIMARY KEY (id),
    CONSTRAINT jogos_plataformas_nome_key UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS public.logs_auditoria
(
    id serial NOT NULL,
    usuario_id integer,
    acao character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tabela_afetada character varying(255) COLLATE pg_catalog."default",
    registro_id integer,
    dados_anteriores jsonb,
    dados_novos jsonb,
    data_acao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ip inet,
    CONSTRAINT logs_auditoria_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mensagens
(
    id serial NOT NULL,
    conversa_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    remetente_id integer NOT NULL,
    destinatario_id integer NOT NULL,
    mensagem text COLLATE pg_catalog."default" NOT NULL,
    anexo_url character varying(255) COLLATE pg_catalog."default",
    data_envio timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    lida boolean DEFAULT false,
    CONSTRAINT mensagens_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notificacoes
(
    id serial NOT NULL,
    usuario_id integer NOT NULL,
    titulo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    mensagem text COLLATE pg_catalog."default" NOT NULL,
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    lida boolean DEFAULT false,
    data_criacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notificacoes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pagamentos
(
    id serial NOT NULL,
    venda_id integer NOT NULL,
    metodo_pagamento character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    valor numeric(10, 2) NOT NULL,
    codigo_transacao character varying(255) COLLATE pg_catalog."default",
    data_pagamento timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    data_confirmacao timestamp with time zone,
    CONSTRAINT pagamentos_pkey PRIMARY KEY (id),
    CONSTRAINT pagamentos_codigo_transacao_key UNIQUE (codigo_transacao),
    CONSTRAINT pagamentos_venda_id_key UNIQUE (venda_id)
);

CREATE TABLE IF NOT EXISTS public.produtos
(
    id serial NOT NULL,
    vendedor_id integer NOT NULL,
    categoria_id integer NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    preco numeric(10, 2) NOT NULL,
    estoque integer NOT NULL DEFAULT 0,
    imagem_url character varying(255) COLLATE pg_catalog."default",
    ativo boolean DEFAULT true,
    destaque boolean DEFAULT false,
    data_cadastro timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT produtos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.produtos_jogos
(
    id serial NOT NULL,
    produto_id integer NOT NULL,
    jogo_id integer NOT NULL,
    servidor character varying(100) COLLATE pg_catalog."default",
    tipo_item character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT produtos_jogos_pkey PRIMARY KEY (id),
    CONSTRAINT produtos_jogos_produto_id_jogo_id_key UNIQUE (produto_id, jogo_id)
);

CREATE TABLE IF NOT EXISTS public.saldo_usuarios
(
    id serial NOT NULL,
    usuario_id integer NOT NULL,
    saldo_disponivel numeric(10, 2) DEFAULT 0.00,
    saldo_a_receber numeric(10, 2) DEFAULT 0.00,
    saldo_total_retirado numeric(10, 2) DEFAULT 0.00,
    data_atualizacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT saldo_usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT saldo_usuarios_usuario_id_key UNIQUE (usuario_id)
);

CREATE TABLE IF NOT EXISTS public.saques
(
    id serial NOT NULL,
    usuario_id integer NOT NULL,
    valor numeric(10, 2) NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    metodo_saque character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dados_saque jsonb,
    comprovante_url character varying(255) COLLATE pg_catalog."default",
    data_solicitacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    data_processamento timestamp with time zone,
    data_conclusao timestamp with time zone,
    CONSTRAINT saques_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    senha_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email_verificado boolean DEFAULT false,
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    data_cadastro timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ultimo_login timestamp with time zone,
    ativo boolean DEFAULT true,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.vendas
(
    id serial NOT NULL,
    vendedor_id integer NOT NULL,
    funcionario_id integer,
    comprador_id integer NOT NULL,
    valor_total numeric(10, 2) NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    data_venda timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vendas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vendedores
(
    id serial NOT NULL,
    usuario_id integer NOT NULL,
    limite_funcionarios integer DEFAULT 5,
    comissao_vendedor numeric(5, 2) DEFAULT 50.00,
    comissao_funcionario numeric(5, 2) DEFAULT 50.00,
    ativo boolean DEFAULT true,
    data_registro timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vendedores_pkey PRIMARY KEY (id),
    CONSTRAINT vendedores_usuario_id_key UNIQUE (usuario_id)
);

ALTER TABLE IF EXISTS public.avaliacoes
    ADD CONSTRAINT avaliacoes_avaliado_id_fkey FOREIGN KEY (avaliado_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_avaliacoes_avaliado_id
    ON public.avaliacoes(avaliado_id);


ALTER TABLE IF EXISTS public.avaliacoes
    ADD CONSTRAINT avaliacoes_avaliador_id_fkey FOREIGN KEY (avaliador_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_avaliacoes_avaliador_id
    ON public.avaliacoes(avaliador_id);


ALTER TABLE IF EXISTS public.avaliacoes
    ADD CONSTRAINT avaliacoes_produto_id_fkey FOREIGN KEY (produto_id)
    REFERENCES public.produtos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_avaliacoes_produto_id
    ON public.avaliacoes(produto_id);


ALTER TABLE IF EXISTS public.avaliacoes
    ADD CONSTRAINT avaliacoes_venda_id_fkey FOREIGN KEY (venda_id)
    REFERENCES public.vendas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.carrinho_compras
    ADD CONSTRAINT carrinho_compras_produto_id_fkey FOREIGN KEY (produto_id)
    REFERENCES public.produtos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_carrinho_compras_produto_id
    ON public.carrinho_compras(produto_id);


ALTER TABLE IF EXISTS public.carrinho_compras
    ADD CONSTRAINT carrinho_compras_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_carrinho_compras_usuario_id
    ON public.carrinho_compras(usuario_id);


ALTER TABLE IF EXISTS public.comissoes_config
    ADD CONSTRAINT comissoes_config_vendedor_id_fkey FOREIGN KEY (vendedor_id)
    REFERENCES public.vendedores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS comissoes_config_vendedor_id_key
    ON public.comissoes_config(vendedor_id);


ALTER TABLE IF EXISTS public.funcionarios_vinculos
    ADD CONSTRAINT funcionarios_vinculos_funcionario_id_fkey FOREIGN KEY (funcionario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.funcionarios_vinculos
    ADD CONSTRAINT funcionarios_vinculos_vendedor_id_fkey FOREIGN KEY (vendedor_id)
    REFERENCES public.vendedores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.itens_venda
    ADD CONSTRAINT itens_venda_produto_id_fkey FOREIGN KEY (produto_id)
    REFERENCES public.produtos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.itens_venda
    ADD CONSTRAINT itens_venda_venda_id_fkey FOREIGN KEY (venda_id)
    REFERENCES public.vendas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_itens_venda_venda_id
    ON public.itens_venda(venda_id);


ALTER TABLE IF EXISTS public.logs_auditoria
    ADD CONSTRAINT logs_auditoria_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_logs_auditoria_usuario_id
    ON public.logs_auditoria(usuario_id);


ALTER TABLE IF EXISTS public.mensagens
    ADD CONSTRAINT mensagens_destinatario_id_fkey FOREIGN KEY (destinatario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_mensagens_destinatario_id
    ON public.mensagens(destinatario_id);


ALTER TABLE IF EXISTS public.mensagens
    ADD CONSTRAINT mensagens_remetente_id_fkey FOREIGN KEY (remetente_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_mensagens_remetente_id
    ON public.mensagens(remetente_id);


ALTER TABLE IF EXISTS public.notificacoes
    ADD CONSTRAINT notificacoes_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_notificacoes_usuario_id
    ON public.notificacoes(usuario_id);


ALTER TABLE IF EXISTS public.pagamentos
    ADD CONSTRAINT pagamentos_venda_id_fkey FOREIGN KEY (venda_id)
    REFERENCES public.vendas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS pagamentos_venda_id_key
    ON public.pagamentos(venda_id);


ALTER TABLE IF EXISTS public.produtos
    ADD CONSTRAINT produtos_categoria_id_fkey FOREIGN KEY (categoria_id)
    REFERENCES public.categorias_produtos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_produtos_categoria_id
    ON public.produtos(categoria_id);


ALTER TABLE IF EXISTS public.produtos
    ADD CONSTRAINT produtos_vendedor_id_fkey FOREIGN KEY (vendedor_id)
    REFERENCES public.vendedores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_produtos_vendedor_id
    ON public.produtos(vendedor_id);


ALTER TABLE IF EXISTS public.produtos_jogos
    ADD CONSTRAINT produtos_jogos_jogo_id_fkey FOREIGN KEY (jogo_id)
    REFERENCES public.jogos_plataformas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_produtos_jogos_jogo_id
    ON public.produtos_jogos(jogo_id);


ALTER TABLE IF EXISTS public.produtos_jogos
    ADD CONSTRAINT produtos_jogos_produto_id_fkey FOREIGN KEY (produto_id)
    REFERENCES public.produtos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_produtos_jogos_produto_id
    ON public.produtos_jogos(produto_id);


ALTER TABLE IF EXISTS public.saldo_usuarios
    ADD CONSTRAINT saldo_usuarios_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS saldo_usuarios_usuario_id_key
    ON public.saldo_usuarios(usuario_id);


ALTER TABLE IF EXISTS public.saques
    ADD CONSTRAINT saques_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_saques_usuario_id
    ON public.saques(usuario_id);


ALTER TABLE IF EXISTS public.vendas
    ADD CONSTRAINT vendas_comprador_id_fkey FOREIGN KEY (comprador_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_vendas_comprador_id
    ON public.vendas(comprador_id);


ALTER TABLE IF EXISTS public.vendas
    ADD CONSTRAINT vendas_funcionario_id_fkey FOREIGN KEY (funcionario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.vendas
    ADD CONSTRAINT vendas_vendedor_id_fkey FOREIGN KEY (vendedor_id)
    REFERENCES public.vendedores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_vendas_vendedor_id
    ON public.vendas(vendedor_id);


ALTER TABLE IF EXISTS public.vendedores
    ADD CONSTRAINT vendedores_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS vendedores_usuario_id_key
    ON public.vendedores(usuario_id);

END;
